### ISSUE TITLE
what  happened ??here   gene_output = td.sess.run(td.gene_moutput, feed_dict=feed_dict) in srez_train.py 

### ISSUE THREAD

**Issue by c1a1o1** [david-gpu/srez#15]
what  happened ??here   gene_output = td.sess.run(td.gene_moutput, feed_dict=feed_dict) in srez_train.py

**Comment by david-gpu** [comment]
If you want to learn Tensorflow this is not the best place. I recommend https://www.tensorflow.org/versions/r0.11/tutorials/index.html
