### ISSUE TITLE
The loss of discriminator are swinging

### ISSUE THREAD

**Issue by hengliusky** [david-gpu/srez#17]
The code is OK. But when I run it, I found the loss of the discriminator (D_Real_loss and D_Fake_loss) are swinging in training. This makes the super-resolved images sometimes good and sometimes bad. 
Perhaps, in my view, this is caused by the calculation way of the generator loss.

**Comment by david-gpu** [comment]
Instability during training is still an open problem with generative adversarial networks, not specific to this implementation. In other words, what you describe sounds like normal behavior.

**Comment by hengliusky** [comment]
Thanks. Since I am a new comer on GAN, what you said extends my knowledge on it. Is it related to the loss of the generator?

**Comment by david-gpu** [comment]
It's an open research question. There are some theories of why this happens but nothing fully conclusive yet. Try reading the most recent papers you can find on GANs.
