### ISSUE TITLE
Moviepy

### ISSUE THREAD

**Issue by sohayla** [david-gpu/srez#23]
i wrote this code and it did not display the video 
i do not now why ?
from moviepy.editor import *
myvideo =  VideoFileClip('C:/Users/Sohayla/Desktop/PythonSourceCode/road_lane_line_detection-master/challenge.MP4').rotate(180)
myvideo.ipython_display()

**Comment by david-gpu** [comment]
Sorry, this doesn't have anything to do with this project. Try asking the moviepy project instead.
