### ISSUE TITLE
FailedPreconditionError: Failed to remove a directory: train

### ISSUE THREAD

**Issue by wai8605** [david-gpu/srez#28]
I do not know why such error occurs like below.
Please give me advice. 

C:\Users\wai\Documents\srez>python srez_main.py --run train
Traceback (most recent call last):
  File "srez_main.py", line 190, in <module>
    tf.app.run()
  File "C:\Users\wai\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "srez_main.py", line 187, in main
    _train()
  File "srez_main.py", line 145, in _train
    all_filenames = prepare_dirs(delete_train_dir=True)
  File "srez_main.py", line 75, in prepare_dirs
    tf.gfile.DeleteRecursively(FLAGS.train_dir)
  File "C:\Users\wai\Anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 366, in delete_recursively
    pywrap_tensorflow.DeleteRecursively(compat.as_bytes(dirname), status)
  File "C:\Users\wai\Anaconda3\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Users\wai\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Failed to remove a directory: train

**Comment by crimsonxiii** [comment]
I had the same issue and fixed it by swapping prepare_dirs and setup_tensorflow in the _train and _demo functions of srez_main.py (sorry, no pull request yet for this). It seems that the creation of the FileWriter in setup_tensorflow causes a file to be created in the train folder, which is kept locked.

**Comment by lemmontea** [comment]
@crimsonxiii Thank you for your answer and attention. I have tried the original code --- used decode_jpeg in srez_input.py . But the error is even more. My tensorflow version is tensorflow-0.12.0rc0-cp35-cp35m-win_amd64, and installed on windows10.

**Comment by crimsonxiii** [comment]
@lemmontea Sorry, I only tested with 1.0 and 1.1. Do you try updating (https://www.tensorflow.org/install/install_windows)?

**Comment by wai8605** [comment]
On a CPU I would try to run non-stop for about a week to get some more decent results training for 130000 batches.
I put results on the site (http://legacy.saloon.jp/page_20170504150038) as ⑦ at any time.

After Batch [4720],some errors occur.
One of them is like below. I do not know the reason.

Progress[  4%], ETA[12465m], Batch [4710], G_Loss[0.210], D_Real_Loss[0.781], D_Fake_Loss[0.246]
Progress[  4%], ETA[12463m], Batch [4720], G_Loss[0.092], D_Real_Loss[0.142], D_Fake_Loss[1.033]
ERROR:tensorflow:Exception in QueueRunner: assertion failed: [Unable to decode bytes as JPEG, PNG, or GIF]
         [[Node: dataset_image/cond_jpeg/cond_png/Assert/Assert = Assert[T=[DT_STRING], summarize=3, _device="/job:localhost/replica:0/task:0/cpu:0"](
dataset_image/cond_jpeg/cond_png/is_gif, dataset_image/cond_jpeg/cond_png/Assert/Assert/data_0)]]

Caused by op 'dataset_image/cond_jpeg/cond_png/Assert/Assert', defined at:
  File "srez_main.py", line 190, in <module>
    tf.app.run()
  File "C:\Users\wai\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 44, in run

**Comment by crimsonxiii** [comment]
@wai8605 '_Unable to decode bytes as JPEG, PNG, or GIF_'. So it seems like again one of your images in the training set is corrupt (not an actual image). It's a pity the callstack doesn't show the parameters or it would be more easy to find which one it is.

**Comment by lemmontea** [comment]
@crimsonxiii I'm sure I've updated TensorFlow. I was using 1.2 because I was windows system, maybe I should use linux. By the way，thank you for your answer！！

**Comment by david-gpu** [comment]
Thank you, @crimsonxiii.
