### ISSUE TITLE
the result of mine is not as good as you showed

### ISSUE THREAD

**Issue by qushaohui** [david-gpu/srez#29]
I download the code and train for 200000 pictures,but the result is not good.this is the end result

Progress[ 71%], ETA[ 168m], Batch [199960], G_Loss[-184.608], D_Real_Loss[-1846.233],
D_Fake_Loss[0.693]
Progress[ 71%], ETA[ 168m], Batch [199970], G_Loss[-184.609], D_Real_Loss[-1846.233], D_Fake_Loss[0.693]
Progress[ 71%], ETA[ 168m], Batch [199980], G_Loss[-184.609], D_Real_Loss[-1846.233], D_Fake_Loss[0.693]
Progress[ 71%], ETA[ 168m], Batch [199990], G_Loss[-184.607], D_Real_Loss[-1846.233], D_Fake_Loss[0.693]
Progress[ 71%], ETA[ 168m], Batch [200000], G_Loss[-184.608], D_Real_Loss[-1846.233], D_Fake_Loss[0.693]

I use the new version of tensorflow,replace some old function.Is this the reason of the bad result?
![batch200000_out](https://cloud.githubusercontent.com/assets/13143586/25302418/1a063f66-2770-11e7-8ff6-d01293d78f05.png)

Sorry to bother you.

**Comment by david-gpu** [comment]
Certainly that doesn't look right. I can't tell what's wrong with it without seeing the changes you've made.
