### ISSUE TITLE
no output an example batch in PNG format on /train folder

### ISSUE THREAD

**Issue by kingson999** [david-gpu/srez#33]
Hi All
The main program running looks well,but no output an example batch in PNG format on /train folder
: 

(C:\ProgramData\Anaconda3\envs\tensorflow) C:\Users\Administrator\AnacondaProjec
ts>d:

(C:\ProgramData\Anaconda3\envs\tensorflow) D:\AI\srez-master>python srez_main.py
 --run train
Progress[ 15%], ETA[  16m], Batch [  10], G_Loss[0.116], D_Real_Loss[0.201], D_F
ake_Loss[2.336]
Progress[ 31%], ETA[  13m], Batch [  20], G_Loss[0.135], D_Real_Loss[0.655], D_F
ake_Loss[1.581]
Progress[ 46%], ETA[  10m], Batch [  30], G_Loss[0.137], D_Real_Loss[0.676], D_F
ake_Loss[1.045]
Progress[ 62%], ETA[   7m], Batch [  40], G_Loss[0.141], D_Real_Loss[0.606], D_F
ake_Loss[0.761]
Progress[ 77%], ETA[   4m], Batch [  50], G_Loss[0.158], D_Real_Loss[0.797], D_F
ake_Loss[0.904]
Progress[ 94%], ETA[   1m], Batch [  60], G_Loss[0.130], D_Real_Loss[0.666], D_F
ake_Loss[0.712]
Progress[109%], ETA[  -1m], Batch [  70], G_Loss[0.135], D_Real_Loss[0.705], D_F
ake_Loss[0.716]
    Checkpoint saved
Finished training!

(C:\ProgramData\Anaconda3\envs\tensorflow) D:\AI\srez-master>

**Comment by kingson999** [comment]
after training fold as : 
![train dir](https://cloud.githubusercontent.com/assets/26153215/26669254/d0da01bc-46df-11e7-8334-b2e8279d8571.png)


my dataset as below:
![dataset](https://cloud.githubusercontent.com/assets/26153215/26669286/ee1e2726-46df-11e7-80f5-61b8f5880edd.png)

**Comment by crimsonxiii** [comment]
See some of the comments in 6cd9a31504ec8bedbfcb67a04562d58ca5768364. Basically if you train on the CPU, then the provided values of long to train and how often to save an example png are too low. Increase train_time and decrease summary_period to see some actual results.

**Comment by kingson999** [comment]
Thanks crimconxiii,  i change the train time and summary_period it works now.

tf.app.flags.DEFINE_integer('train_time', 240,
                            "Time in minutes to train the model")

tf.app.flags.DEFINE_integer('summary_period', 5,
                            "Number of batches between summary data dumps")
