### ISSUE TITLE
request

### ISSUE THREAD

**Issue by YukiZhang15** [david-gpu/srez#36]
DearDavid，
    I'm studing at Jilin University in China and Majored in Face Recognition. Could  you please tell me which paper this code is based on? And may I have the model that has trained already?  It would be so great of you. Thanks a lot.

**Comment by david-gpu** [comment]
This repo is not based on one particular paper, but is related to a number of them.

If you specifically want to read a paper, I suggest reading https://arxiv.org/abs/1609.04802 which does reference this repo as their method is somewhat similar to this.

Sorry I can't provide you with a trained model. I no longer maintain this repo.
