### ISSUE TITLE
discriminator model does not resemble with original paper's model

### ISSUE THREAD

**Issue by plopd** [david-gpu/srez#37]
The discriminator does not match with the original paper's model shown in the figure below, right?
E.g. Strided convolutions are not used to reduce the image resolution each time the number of features is doubled.
Also the first conv layer k3n64s1 followed by leakyReLU are not added before the blocks.

<img width="648" alt="screen shot 2017-07-09 at 18 08 45" src="https://user-images.githubusercontent.com/1534513/27995714-4dd47312-64d3-11e7-95a1-d27d8f38af5b.png">

**Comment by david-gpu** [comment]
This project is not exactly based on any particular paper, although it's of course influenced by a number of them.
