### ISSUE TITLE
FileNotFoundError: Could not find folder `checkpoint'

### ISSUE THREAD

**Issue by Aaronfree** [david-gpu/srez#39]
Dear David Garcia,
I'm so sorry to bother you . When I run your code, It has such error:

D:\Users\aaron\Anaconda3\python.exe E:/Code/srez/srez_main.py
Traceback (most recent call last):
  File "E:/Code/srez/srez_main.py", line 191, in <module>
    tf.app.run()
  File "D:\Users\aaron\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "E:/Code/srez/srez_main.py", line 186, in main
    _demo()
  File "E:/Code/srez/srez_main.py", line 111, in _demo
    raise FileNotFoundError("Could not find folder `%s'" % (FLAGS.checkpoint_dir,))
FileNotFoundError: Could not find folder `checkpoint'

It seems that I dont create checkpoint dir or train dir in a right way, but how can I solve it?
THX

**Comment by tstc435** [comment]
It seems you didn't train the mode firstly.

**Comment by gaochonga** [comment]
I have run the "serz_train",but no checkpoint be output.

**Comment by zhouky146** [comment]
Have you solved it yet?

**Comment by maheshi81** [comment]
Let me know if this is solved, please
