### ISSUE TITLE
Dropbox account holding the training data is temporarily suspended because of heavy traffic.

### ISSUE THREAD

**Issue by manoharprabhu** [david-gpu/srez#4]
Is it feasible to host the training data somewhere else?

**Comment by david-gpu** [comment]
Thank you for the notice. I have contacted the authors of the dataset. I don't think it can be downloaded from any other publicly accessible place because the authors explicitly asked folks not to redistribute it.

The situation will probably be resolved in a few days. Sorry for the trouble.

**Comment by weirwolf** [comment]
I was able to successfully obtain the dataset from Google Drive as per the authors: https://drive.google.com/open?id=0B7EVK8r0v71pWEZsZE9oNnFzTm8

**Comment by david-gpu** [comment]
Thank you, weirwolf. Closing.
