### ISSUE TITLE
How to test trained model on single face image?

### ISSUE THREAD

**Issue by JachenL** [david-gpu/srez#51]

**Comment by FadedCosine** [comment]
do you know how to test trained model on single face image now? Wait for your reply sincerely.

**Comment by suton5** [comment]
Have there been any updates on this?

**Comment by GUANGMINGSHI** [comment]
I'm also doing this, do you know how to do it?

**Comment by TataMoktari** [comment]
I am also interested to test an image on trained model. your kind help is appreciated.

**Comment by aezco** [comment]
Did you solve it?
