### ISSUE TITLE
Only call `sigmoid_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)

### ISSUE THREAD

**Issue by lishangxuexi** [david-gpu/srez#52]
I try to run the project by typing the suggested codes "python3 srez_main.py --run train"
but failed with the message " ValueError: Only call `sigmoid_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)
![default](https://user-images.githubusercontent.com/38323175/39438515-04eff56c-4cd7-11e8-9765-cc8d78b52cb5.JPG)
"

Sincerely look for your help~

**Comment by Lxyzgf** [comment]
@lishangxuexi  
 hi, the correct function  is : 
tf.nn.sigmoid_cross_entropy_with_logits(logits=disc_real_output, labels=tf.ones_like(disc_real_output)).
 You should figure out the parameters: logits and labels

**Comment by lishangxuexi** [comment]
Thank U very much ！！！！

**Comment by amrbenattia** [comment]
I am training this model but while training I got this error

Use `tf.global_variables_initializer` instead.
Progress[  0%], ETA[  19m], Batch [  10], G_Loss[0.285], D_Real_Loss[2.041], D_Fake_Loss[0.195]
Progress[  0%], ETA[  19m], Batch [  20], G_Loss[0.215], D_Real_Loss[1.224], D_Fake_Loss[0.805]
Progress[  0%], ETA[  19m], Batch [  30], G_Loss[0.175], D_Real_Loss[1.012], D_Fake_Loss[0.578]
Progress[  0%], ETA[  19m], Batch [  40], G_Loss[0.149], D_Real_Loss[0.779], D_Fake_Loss[0.711]
Progress[  1%], ETA[  19m], Batch [  50], G_Loss[0.114], D_Real_Loss[0.566], D_Fake_Loss[0.996]
Progress[  1%], ETA[  19m], Batch [  60], G_Loss[0.124], D_Real_Loss[0.754], D_Fake_Loss[0.666]
Progress[  1%], ETA[  19m], Batch [  70], G_Loss[0.117], D_Real_Loss[0.659], D_Fake_Loss[0.701]
Progress[  1%], ETA[  19m], Batch [  80], G_Loss[0.130], D_Real_Loss[0.496], D_Fake_Loss[0.728]
Progress[  1%], ETA[  19m], Batch [  90], G_Loss[0.118], D_Real_Loss[0.629], D_Fake_Loss[0.701]
Progress[  2%], ETA[  19m], Batch [ 100], G_Loss[0.123], D_Real_Loss[0.675], D_Fake_Loss[0.667]
Progress[  2%], ETA[  19m], Batch [ 110], G_Loss[0.109], D_Real_Loss[0.625], D_Fake_Loss[0.791]
Progress[  2%], ETA[  19m], Batch [ 120], G_Loss[0.113], D_Real_Loss[0.729], D_Fake_Loss[0.767]
Progress[  2%], ETA[  19m], Batch [ 130], G_Loss[0.153], D_Real_Loss[0.977], D_Fake_Loss[0.673]
Progress[  2%], ETA[  19m], Batch [ 140], G_Loss[0.139], D_Real_Loss[0.821], D_Fake_Loss[0.566]
Progress[  2%], ETA[  19m], Batch [ 150], G_Loss[0.125], D_Real_Loss[0.757], D_Fake_Loss[0.657]
Progress[  3%], ETA[  19m], Batch [ 160], G_Loss[0.139], D_Real_Loss[0.694], D_Fake_Loss[0.657]
Progress[  3%], ETA[  19m], Batch [ 170], G_Loss[0.126], D_Real_Loss[0.719], D_Fake_Loss[0.635]
Progress[  3%], ETA[  19m], Batch [ 180], G_Loss[0.119], D_Real_Loss[0.663], D_Fake_Loss[0.744]
Progress[  3%], ETA[  19m], Batch [ 190], G_Loss[0.130], D_Real_Loss[0.865], D_Fake_Loss[0.682]
Progress[  3%], ETA[  19m], Batch [ 200], G_Loss[0.118], D_Real_Loss[0.758], D_Fake_Loss[0.596]
Traceback (most recent call last):
  File "./srez_main.py", line 190, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "./srez_main.py", line 187, in main
    _train()
  File "./srez_main.py", line 179, in _train
    srez_train.train_model(train_data)
  File "/content/srez_train.py", line 107, in train_model
    _summarize_progress(td, test_feature, test_label, gene_output, batch, 'out')
  File "/content/srez_train.py", line 22, in _summarize_progress
    image   = tf.concat(2, [nearest, bicubic, clipped, label])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py", line 1254, in concat
    tensor_shape.scalar())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_shape.py", line 1023, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (4, 16, 64, 64, 3) and () are incompatible
