### ISSUE TITLE
ValueError: string_input_producer requires a non-null input tensor

### ISSUE THREAD

**Issue by tuanl12** [david-gpu/srez#54]
![screen shot 2018-07-14 at 11 49 05 am](https://user-images.githubusercontent.com/38969089/42726045-fd2ab140-875b-11e8-9b75-6498e787893d.png)
When I run "python3 srez_main.py --run train", I encountered a "ValueError: string_input_producer requires a non-null input tensor," as shown in the above. Can someone please help me fix it? Does the original code not work??

**Comment by NathanZhang1104** [comment]
The dataset shouldn't be empty,but I don't know how to solute
