### ISSUE TITLE
D_Fake_Loss does not change at all

### ISSUE THREAD

**Issue by mew124** [david-gpu/srez#61]
I made the changes proposed to update the code to TensorFlow 1.2.1, but now I have the problem that D_Fake_Loss does not change at all during training and stays at 0.693, while D_Real_Loss gets very negative. Does anyone have an idea, what might be causing this problem and how to get rid of it?

I use tensorflow 1.2.1, numpy 1.16.3, scipy 1.3.0, six 1.10.0, moviepy 1.0.0

Thank you!

![screenshot_anaconda_promt_300min7](https://user-images.githubusercontent.com/45708530/59051968-57209f00-888e-11e9-8587-8711d3713823.PNG)

**Comment by nuthangardas** [comment]
Hey, Did you get to know anything about it?

**Comment by Howie86** [comment]
Have you solved it? I met the same problem, if you have solved it, please tell me. 
Thank you!
